samples:
    ctrl_rep1:
        R1: "data/raw/ctrl_rep1_R1.fastq.gz"
        R2: "data/raw/ctrl_rep1_R2.fastq.gz"
    ctrl_rep2:
        R1: "data/raw/ctrl_rep2_R1.fastq.gz"
        R2: "data/raw/ctrl_rep2_R2.fastq.gz"
    exp_rep1:
        R1: "data/raw/exp_rep1_R1.fastq.gz"
        R2: "data/raw/exp_rep1_R2.fastq.gz"
    exp_rep2:
        R1: "data/raw/exp_rep2_R1.fastq.gz"
        R2: "data/raw/exp_rep2_R2.fastq.gz"

threads: 8
trinity_memory: "30G"
